#The domain prefix for ldap
openldap_server_domain_name: green.local

#This is the password for admin for openldap 
openldap_server_rootpw: letmein

#The self signed ssl parameters
openldap_server_country: BE
openldap_server_state: oostvlaanderen
openldap_server_location: gent
openldap_server_organization: IT

openldap_server_enable_ssl: false

#ldap-config configuration
default_user_password: letmein

openldap_create_organizationalunits:
  - Afdelingen

openldap_create_groups:
  - name: IT_Administratie
    gid: 1001
    group_ou: ou=Afdelingen
  - name: Verkoop
    gid: 1002
    group_ou: ou=Afdelingen
  - name: Administratie
    gid: 1003
    group_ou: ou=Afdelingen
  - name: Ontwikkeling
    gid: 1004
    group_ou: ou=Afdelingen
  - name: Directie
    gid: 1005
    group_ou: ou=Afdelingen

openldap_create_users:
  - name: milan
    cn: Milan Dewilde
    sn: Dewilde
    password: milan
    email: dewilde.milan@hotmail.com
    group_ou: ou=Afdelingen
    uidNumber: 1501

openldap_add_uniquemember:
  - name: milan
    member_dn: uid=milan,ou=Afdelingen
    group_dn: cn=default-users,ou=Afdelingen

#389-directory configuration
dirsrv_fqdn: alfa1.green.local
dirsrv_password: letmeintomyserver

# Monitoring configuration
# prometheus_servers:
#   - 172.16.1.5
# prometheus_components:
#   - openldap_exporter_tomcz
# prometheus_openldap_exporter_tomcz_port: 9330
# prometheus_openldap_exporter_tomcz_extra_opts: []