---

mariadb_databases: 
  - name: drupal_echo1 
  - name: drupal_mike1

mariadb_users: 
  - name: echo1_user
    password: echo1
    priv: 'drupal_echo1.*:ALL'
    append_privs: 'yes'        
    host: '172.16.1.69'
  - name: mike1_user
    password: mike1
    priv: 'drupal_mike1.*:ALL'
    append_privs: 'yes'
    host: '172.16.1.3'   

mariadb_root_password: admin

mariadb_bind_address: '0.0.0.0'