---
rhbase_firewall_allow_services:
  - http
  - https
rhbase_firewall_allow_ports:
  - 9090/tcp
  - 3000/tcp
  - 9116/tcp

dns_nameservers: ['172.16.1.66', '10.0.2.3']

prometheus_scrape_jobs:
  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 172.16.1.97
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.
prometheus_targets:
  node:
  - targets:
    - alpha1.green.local:9100
    - bravo1.green.local:9100
    - charlie1.green.local:9100
    - delta1.green.local:9100
    - echo1.green.local:9100
    - kilo1.green.local:9100
    - lima1.green.local:9100
    - mike1.green.local:9100
    - november1.green.local:9100
    - oscar1.green.local:9100
    - papa1.green.local:9100
    - zulu1.green.local:9100
#    - 172.16.1.5:9100 # Node exporter oscar1
#    - 172.16.1.67:9100 # Node exporter charlie1
    labels:
      env: green.local
grafana_security:
  admin_user: admin
  admin_password: oscar1
grafana_datasources:
  - name: "prometheus"
    type: "prometheus"
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false
grafana_dashboards:
  - dashboard_id: 10645
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 2939
    revision_id: 8
    datasource: 'prometheus'
  - dashboard_id: 9901
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 1666
    revision_id: 1
    datasource: 'prometheus'
  - dashboard_id: 9908
    revision_id: 1
    datasource: 'prometheus'
