---
rhbase_firewall_allow_services:
  - http
  - https
rhbase_firewall_allow_ports:
  - 9090/tcp
  - 3000/tcp
  - 9116/tcp

dns_nameservers: 
  - 172.16.1.66 
  - 10.0.2.3

# prometheus_targets:
#   node:
#   - targets:
#     - alpha1.green.local:9100
#     - bravo1.green.local:9100
#     - charlie1.green.local:9100
#     - delta1.green.local:9100
#     - echo1.green.local:9100
#     - kilo1.green.local:9100
#     - lima1.green.local:9100
#     - mike1.green.local:9100
#     - november1.green.local:9100
#     - oscar1.green.local:9100
#     - papa1.green.local:9100
#     - zulu1.green.local:9100
# #    - 172.16.1.5:9100 # Node exporter oscar1
# #    - 172.16.1.67:9100 # Node exporter charlie1
#     labels:
#       env: green.local

prometheus_scrape_configs:
  # - job_name: "bind"
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets:
  #       - charlie1.green.local:8053
  - job_name: "prometheus"    # Custom scrape job, here using `static_config`
    metrics_path: "/metrics"
    static_configs:
      - targets:
          # - "localhost:9090"
          - alpha1.green.local:9100
          - bravo1.green.local:9100
          - charlie1.green.local:9100
          - delta1.green.local:9100
          - echo1.green.local:9100
          - kilo1.green.local:9100
          - lima1.green.local:9100
          - mike1.green.local:9100
          - november1.green.local:9100
          - oscar1.green.local:9100
          - papa1.green.local:9100
          - quebec1.green.local:9100
  # - job_name: "servicediscovery"
  #   file_sd_configs:
  #     - files:
  #         - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from `prometheus_targets`
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 172.16.1.97  # SNMP device.
        - 172.16.1.98
        - 172.16.1.80
        - 172.16.1.50
        - 172.16.0.80
        - zulu1.green.local
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.1.5:9116  # The SNMP exporter's real hostname:port.

grafana_security:
  admin_user: admin
  admin_password: oscar1
grafana_datasources:
  - name: "prometheus"
    type: "prometheus"
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false
grafana_dashboards:
  - dashboard_id: 405 # Algemeen
    revision_id: 8
    datasource: 'prometheus' 
  - dashboard_id: 1860 # Node exporter full, 1 server tegelijk
    revision_id: 15
    datasource: 'prometheus' 
  - dashboard_id: 2408 # SNMP Interface throughput
    revision_id: 1
    datasource: 'prometheus'
  # - dashboard_id: 1666
  #   revision_id: 1
  #   datasource: 'prometheus'
